default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  host: db
  pool: 5

development:
  <<: *default
  database: ready_set_jet_development
test:
  <<: *default
  database: ready_set_jet_test

production:
  <<: *default
  database: ready_set_jet_production
  username: ready_set_jet
  password: <%= ENV['READY_SET_JET_DATABASE_PASSWORD'] %>